# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catalogo_especies.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 473)
        MainWindow.setStyleSheet("background-color: rgb(14, 118, 66);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(14, 14, 771, 441))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cadastro_especie = QtWidgets.QWidget()
        self.tab_cadastro_especie.setObjectName("tab_cadastro_especie")
        self.label_nome = QtWidgets.QLabel(self.tab_cadastro_especie)
        self.label_nome.setGeometry(QtCore.QRect(10, 10, 110, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.entry_nome = QtWidgets.QLineEdit(self.tab_cadastro_especie)
        self.entry_nome.setGeometry(QtCore.QRect(130, 10, 251, 20))
        self.entry_nome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"border-radius:5px;")
        self.entry_nome.setObjectName("entry_nome")
        self.label_status = QtWidgets.QLabel(self.tab_cadastro_especie)
        self.label_status.setGeometry(QtCore.QRect(10, 46, 110, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.comboBox = QtWidgets.QComboBox(self.tab_cadastro_especie)
        self.comboBox.setGeometry(QtCore.QRect(130, 40, 151, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tabWidget.addTab(self.tab_cadastro_especie, "")
        self.tab_relatorio = QtWidgets.QWidget()
        self.tab_relatorio.setObjectName("tab_relatorio")
        self.label_nome_especie = QtWidgets.QLabel(self.tab_relatorio)
        self.label_nome_especie.setGeometry(QtCore.QRect(17, 30, 110, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nome_especie.setFont(font)
        self.label_nome_especie.setObjectName("label_nome_especie")
        self.entry_nome_especie = QtWidgets.QLineEdit(self.tab_relatorio)
        self.entry_nome_especie.setGeometry(QtCore.QRect(140, 30, 141, 20))
        self.entry_nome_especie.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"border-radius:6px;")
        self.entry_nome_especie.setObjectName("entry_nome_especie")
        self.tabWidget.addTab(self.tab_relatorio, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_nome.setText(_translate("MainWindow", "Nome da Espécie:"))
        self.label_status.setText(_translate("MainWindow", "Nível de Extinção:"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Crítico"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Em Perigo"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Vulnerável"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Pouco Preocupante"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cadastro_especie), _translate("MainWindow", "Especies"))
        self.label_nome_especie.setText(_translate("MainWindow", "Nome da Espécie: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_relatorio), _translate("MainWindow", "Relatório"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
